export const movies = [
  {
    id: "1",
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    views: 124500,
    year: 2014,
    matchRate: 98,
    ageRating: "13+",
    duration: "2h 49m",
    ratings: [
      { user: "john", score: 5 },
      { user: "alice", score: 4 },
      { user: "somchai", score: 5 },
    ],
  },
  {
    id: "2",
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    category: "Action",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    views: 95400,
    year: 2008,
    matchRate: 99,
    ageRating: "16+",
    duration: "2h 32m",
    ratings: [
      { user: "mark", score: 5 },
      { user: "kitti", score: 5 },
    ],
  },
  {
    id: "3",
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    views: 110200,
    year: 2010,
    matchRate: 97,
    ageRating: "13+",
    duration: "2h 28m",
    ratings: [
      { user: "sam", score: 4 },
      { user: "chao", score: 5 },
    ],
  },
  {
    id: "4",
    title: "The Conjuring",
    description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    category: "Horror",
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=k10ETZ42q5o",
    views: 82000,
    year: 2013,
    matchRate: 94,
    ageRating: "18+",
    duration: "1h 52m",
    ratings: [
      { user: "ghosthunter", score: 4 },
      { user: "scaredycat", score: 3 },
    ],
  },
  {
    id: "5",
    title: "The Hangover",
    description: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=tcdUhdOlz9M",
    views: 74000,
    year: 2009,
    matchRate: 92,
    ageRating: "18+",
    duration: "1h 40m",
    ratings: [
      { user: "laughoutloud", score: 5 },
      { user: "grumpy", score: 2 },
    ],
  },
  {
    id: "6",
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    category: "Thriller",
    thumbnail: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    views: 89000,
    year: 2019,
    matchRate: 96,
    ageRating: "18+",
    duration: "2h 12m",
    ratings: [
      { user: "cinephile", score: 5 },
      { user: "bongjoonho", score: 5 },
    ],
  },
  {
    id: "7",
    title: "Shutter",
    description: "A young photographer and his girlfriend discover mysterious shadows in their photographs after a tragic road accident.",
    category: "Horror",
    thumbnail: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=yW6aKj-4E0s",
    views: 63000,
    year: 2004,
    matchRate: 95,
    ageRating: "18+",
    duration: "1h 37m",
    ratings: [
      { user: "ananda", score: 5 },
      { user: "horrorgirl", score: 4 },
    ],
  },
  {
    id: "8",
    title: "Bad Genius",
    description: "Lynn, a genius high school student who makes money by cheating tests, receives a new task that leads her to set foot on Sydney, Australia.",
    category: "Thriller",
    thumbnail: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=CLek_u8tU4g",
    views: 91000,
    year: 2017,
    matchRate: 98,
    ageRating: "13+",
    duration: "2h 10m",
    ratings: [
      { user: "student", score: 5 },
      { user: "teacher", score: 4 },
    ],
  },
  {
    id: "9",
    title: "Pee Mak",
    description: "Mak returns from war to invite his friends to meet his beautiful wife Nak. But rumors start spreading that Nak is actually a ghost.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=vVj4I7pX_P4",
    views: 120000,
    year: 2013,
    matchRate: 97,
    ageRating: "13+",
    duration: "1h 55m",
    ratings: [
      { user: "mario", score: 5 },
      { user: "davika", score: 5 },
    ],
  },
  {
    id: "10",
    title: "Avatar: The Way of Water",
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns, Jake must work with Neytiri to protect their home.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=d9MyW72ELq0",
    views: 114000,
    year: 2022,
    matchRate: 95,
    ageRating: "13+",
    duration: "3h 12m",
    ratings: [
      { user: "pandoran", score: 4 },
      { user: "scifi_fan", score: 5 },
    ],
  },
  {
    id: "11",
    title: "Dune: Part Two",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    views: 108000,
    year: 2024,
    matchRate: 99,
    ageRating: "13+",
    duration: "2h 46m",
    ratings: [
      { user: "muad_dib", score: 5 },
      { user: "spicemelange", score: 5 },
    ],
  },
  {
    id: "12",
    title: "Gladiator II",
    description: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum.",
    category: "Action",
    thumbnail: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=gT8wNskC6i0",
    views: 87000,
    year: 2024,
    matchRate: 91,
    ageRating: "18+",
    duration: "2h 28m",
    ratings: [
      { user: "romefan", score: 4 },
      { user: "emperor", score: 4 },
    ],
  },
  {
    id: "13",
    title: "Mad Max: Fury Road",
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.",
    category: "Action",
    thumbnail: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
    views: 99000,
    year: 2015,
    matchRate: 98,
    ageRating: "16+",
    duration: "2h 0m",
    ratings: [
      { user: "roadwarrior", score: 5 },
      { user: "imperator", score: 5 },
    ],
  },
  {
    id: "14",
    title: "John Wick: Chapter 4",
    description: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy.",
    category: "Action",
    thumbnail: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=qEVUtrk8_B4",
    views: 104000,
    year: 2023,
    matchRate: 97,
    ageRating: "18+",
    duration: "2h 49m",
    ratings: [
      { user: "doglover", score: 5 },
      { user: "baba_yaga", score: 5 },
    ],
  },
  {
    id: "15",
    title: "A Quiet Place",
    description: "A family struggles for survival in a world where most humans have been killed by blind but noise-sensitive creatures.",
    category: "Horror",
    thumbnail: "https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=WR7cc5t7tvA",
    views: 79000,
    year: 2018,
    matchRate: 93,
    ageRating: "16+",
    duration: "1h 30m",
    ratings: [
      { user: "silence", score: 4 },
      { user: "shh", score: 4 },
    ],
  },
  {
    id: "16",
    title: "Get Out",
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception eventually reaches a boiling point.",
    category: "Thriller",
    thumbnail: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=DxHCyeGZas8",
    views: 86000,
    year: 2017,
    matchRate: 96,
    ageRating: "18+",
    duration: "1h 44m",
    ratings: [
      { user: "peele_fan", score: 5 },
      { user: "sunkenplace", score: 4 },
    ],
  },
  {
    id: "17",
    title: "Knives Out",
    description: "A detective investigates the death of the patriarch of an eccentric, combative family.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=qGqiHJTsRkQ",
    views: 93000,
    year: 2019,
    matchRate: 95,
    ageRating: "13+",
    duration: "2h 10m",
    ratings: [
      { user: "murdermystery", score: 5 },
      { user: "blanc", score: 4 },
    ],
  },
  {
    id: "18",
    title: "The Matrix",
    description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    views: 119000,
    year: 1999,
    matchRate: 99,
    ageRating: "16+",
    duration: "2h 16m",
    ratings: [
      { user: "morpheus", score: 5 },
      { user: "redpill", score: 5 },
    ],
  },
  {
    id: "19",
    title: "Train to Busan",
    description: "While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.",
    category: "Horror",
    thumbnail: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=pyWuHv2-Y8s",
    views: 97000,
    year: 2016,
    matchRate: 97,
    ageRating: "16+",
    duration: "1h 58m",
    ratings: [
      { user: "zombie_killer", score: 5 },
      { user: "gongyoo", score: 5 },
    ],
  },
  {
    id: "20",
    title: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=cqGjhVJWtEg",
    views: 106000,
    year: 2023,
    matchRate: 98,
    ageRating: "PG",
    duration: "2h 20m",
    ratings: [
      { user: "spidey", score: 5 },
      { user: "spidergwen", score: 5 },
    ],
  },
  {
    id: "21",
    title: "Blade Runner 2049",
    description: "A new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    category: "Sci-Fi",
    thumbnail: "https://images.unsplash.com/photo-1515621061946-eff1c2a352bd?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=gCcx85zbxz4",
    views: 92000,
    year: 2017,
    matchRate: 96,
    ageRating: "16+",
    duration: "2h 44m",
    ratings: [
      { user: "officer_k", score: 5 },
      { user: "replicant", score: 4 },
    ],
  },
  {
    id: "22",
    title: "The Medium (ร่างทรง)",
    description: "A horrifying story of a shaman's inheritance in the Isan region of Thailand, where a family member's demonic possession turns extremely dark.",
    category: "Horror",
    thumbnail: "https://images.unsplash.com/photo-1508333706533-1ab43ecb1606?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=kR2pYdM6N7g",
    views: 88000,
    year: 2021,
    matchRate: 94,
    ageRating: "18+",
    duration: "2h 10m",
    ratings: [
      { user: "narilya", score: 5 },
      { user: "spiritist", score: 4 },
    ],
  },
  {
    id: "23",
    title: "Home Stay",
    description: "A wandering spirit gets a second chance at life inside the body of a high school student named Min, but has only 100 days to solve Min's death.",
    category: "Thriller",
    thumbnail: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=4C2wE_L_yT0",
    views: 79000,
    year: 2018,
    matchRate: 95,
    ageRating: "13+",
    duration: "2h 16m",
    ratings: [
      { user: "james_fm", score: 4 },
      { user: "gdh_lover", score: 5 },
    ],
  },
  {
    id: "24",
    title: "SuckSeed (ห่วยขั้นเทพ)",
    description: "Three high school students form an amateur rock band to impress a girl, learning about friendship, love, and dreams along the way.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=2r7d7CgV2hI",
    views: 94000,
    year: 2011,
    matchRate: 96,
    ageRating: "13+",
    duration: "2h 10m",
    ratings: [
      { user: "rockstar", score: 5 },
      { user: "ped", score: 5 },
    ],
  },
  {
    id: "25",
    title: "One Day (แฟนเดย์)",
    description: "An IT geek gets a one-day chance to pretend to be the boyfriend of his dream girl who suffers from temporary memory loss.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=W0-h3P576bE",
    views: 89000,
    year: 2016,
    matchRate: 97,
    ageRating: "13+",
    duration: "1h 51m",
    ratings: [
      { user: "ter_chantavit", score: 5 },
      { user: "mew_nittha", score: 5 },
    ],
  },
  {
    id: "26",
    title: "Friend Zone (ระวัง..สิ้นสุดทางเพื่อน)",
    description: "A man who has been stuck in the friend zone with his best friend for ten years tries to break out and confess his feelings.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1472214222541-d510753a8707?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=x7nN2M4f14M",
    views: 92000,
    year: 2019,
    matchRate: 96,
    ageRating: "13+",
    duration: "2h 0m",
    ratings: [
      { user: "gink", score: 5 },
      { user: "palm", score: 4 },
    ],
  },
  {
    id: "27",
    title: "4BIAS (สี่แพร่ง)",
    description: "An omnibus of four ghost stories that will freeze your blood, exploring supernatural isolation, vengeance, dark talismans, and royal curse.",
    category: "Horror",
    thumbnail: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=7W-15bM_JkU",
    views: 81000,
    year: 2008,
    matchRate: 94,
    ageRating: "18+",
    duration: "1h 57m",
    ratings: [
      { user: "ghosthunter", score: 5 },
      { user: "spooky", score: 4 },
    ],
  },
  {
    id: "28",
    title: "13 Beloved (13 เกมสยอง)",
    description: "An indebted salesman receives a mysterious call inviting him to play a 13-stage real-life game show with escalating horror for million-dollar rewards.",
    category: "Thriller",
    thumbnail: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=Vl0353W-q8E",
    views: 83000,
    year: 2006,
    matchRate: 95,
    ageRating: "18+",
    duration: "1h 54m",
    ratings: [
      { user: "krissada", score: 5 },
      { user: "mastermind", score: 5 },
    ],
  },
  {
    id: "29",
    title: "Top Secret (วัยรุ่นพันล้าน)",
    description: "The inspiring true story of a young Thai gamer who dropped out of school to build a seaweed snack empire amidst massive family debt.",
    category: "Thriller",
    thumbnail: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=1FfN5l2aI9k",
    views: 88000,
    year: 2011,
    matchRate: 98,
    ageRating: "13+",
    duration: "2h 4m",
    ratings: [
      { user: "taokaenoi", score: 5 },
      { user: "businessman", score: 4 },
    ],
  },
  {
    id: "30",
    title: "ATM: Er Rak Error",
    description: "A comical bank employee couple hides their relationship due to corporate regulations, leading to a frantic chase over a malfunctioning ATM.",
    category: "Comedy",
    thumbnail: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1000",
    youtubeUrl: "https://www.youtube.com/watch?v=1CjFzK30hR8",
    views: 95000,
    year: 2012,
    matchRate: 97,
    ageRating: "13+",
    duration: "2h 2m",
    ratings: [
      { user: "atm_user", score: 5 },
      { user: "cashier", score: 5 },
    ],
  }
];
