export const LOCALIZATION = {
  LOADING: {
    DELETE_CREW: "กำลังลบข้อมูลทีมงาน...",
    DELETE_MOVIE: "กำลังลบภาพยนตร์...",
    SAVE_CREW: "กำลังบันทึกข้อมูลทีมงาน...",
    SAVE_MOVIE: "กำลังบันทึกภาพยนตร์...",
    SUB_DELETE_CREW: "กรุณารอสักครู่ ระบบกำลังลบข้อมูลทีมงานออกจากระบบ",
    SUB_DELETE_MOVIE: "กรุณารอสักครู่ ระบบกำลังลบภาพยนตร์ออกจากระบบคลัง",
    SUB_SAVE_CREW: "กรุณารอสักครู่ ระบบกำลังอัปโหลดข้อมูลและรูปภาพทีมงาน",
    SUB_SAVE_MOVIE: "กรุณารอสักครู่ ระบบกำลังอัปโหลดข้อมูลและจัดเก็บภาพปก",
  },
  CREW_FORM: {
    EDIT_TITLE: "แก้ไขข้อมูลทีมงาน",
    ADD_TITLE: "เพิ่มทีมงาน / นักแสดงใหม่",
    SUBTITLE:
      "กรอกข้อมูลเพื่อลงทะเบียนทีมงานหรือนักแสดงเข้าสู่ระบบคลังเพื่อใช้เป็นตัวเลือกสำหรับภาพยนตร์เรื่องต่างๆ",
    NAME_LABEL: "ชื่อ-นามสกุล",
    NAME_PLACEHOLDER: "เช่น สมชาย ใจดี",
    PHOTO_LABEL: "รูปภาพประจำตัว",
    PHOTO_PLACEHOLDER: "เลือกรูปภาพประจำตัว...",
    BROWSE: "เลือกไฟล์",
    CANCEL: "ยกเลิก",
    SAVE: "บันทึกการแก้ไข",
    ADD: "เพิ่มรายชื่อ",
    PREVIEW_TITLE: "รูปภาพประจำตัวที่ใช้",
    PREVIEW_CROPPED: "รูปภาพหลังแก้ไข",
    PREVIEW_ORIGINAL: "รูปภาพปัจจุบัน",
    RECROP: "แก้ไขรูปภาพอีกครั้ง",
    CURRENT_SYSTEM: "รูปภาพในระบบ",
  },
  TOAST: {
    EDIT_MOVIE_SUCCESS: "แก้ไขข้อมูลภาพยนตร์เรียบร้อยแล้ว",
    ADD_MOVIE_SUCCESS: "เพิ่มภาพยนตร์เข้าสู่ระบบเรียบร้อยแล้ว",
    DELETE_MOVIE_SUCCESS: "ลบภาพยนตร์ออกจากระบบเรียบร้อยแล้ว",
    EDIT_CREW_SUCCESS: "แก้ไขข้อมูลทีมงานเรียบร้อยแล้ว",
    ADD_CREW_SUCCESS: "เพิ่มข้อมูลทีมงานเรียบร้อยแล้ว",
    DELETE_CREW_SUCCESS: "ลบข้อมูลทีมงานเรียบร้อยแล้ว",
    REQUIRED_NAME: "กรุณากรอกชื่อทีมงาน",
  },
  ERRORS: {
    SAVE: "เกิดข้อผิดพลาดในการบันทึกข้อมูล",
    DELETE: "เกิดข้อผิดพลาดในการลบข้อมูล",
    SAVE_MOVIE: "เกิดข้อผิดพลาดในการบันทึกภาพยนตร์",
  },
  CONFIRM: {
    DELETE_CREW_TITLE: "ยืนยันการลบ",
    DELETE_CREW_MSG:
      "การดำเนินการนี้จะเป็นแบบถาวรและไม่สามารถกู้คืนได้ การลบรายชื่อนี้อาจส่งผลต่อข้อมูลของภาพยนตร์เรื่องอื่นๆ ที่ทีมงานท่านนี้มีส่วนร่วมอยู่",
    DELETE_CREW_BTN: "ลบรายชื่อทีมงาน",
    DELETE_MOVIE_TITLE: "ยืนยันการลบข้อมูล",
    DELETE_MOVIE_MSG:
      "การดำเนินการนี้ไม่สามารถย้อนกลับได้ ภาพยนตร์เรื่องที่เลือกจะถูกลบออกจากฐานข้อมูลระบบและคลังฉายภาพยนตร์ทันที",
    DELETE_MOVIE_BTN: "ยืนยัน",
    EDIT_CREW_TITLE: "ยืนยันการแก้ไข",
    ADD_CREW_TITLE: "ยืนยันการเพิ่ม",
    EDIT_CREW_MSG: (name: string) =>
      `คุณแน่ใจหรือไม่ว่าต้องการบันทึกการแก้ไขข้อมูลของ "${name}"?`,
    ADD_CREW_MSG: (name: string) =>
      `คุณแน่ใจหรือไม่ว่าต้องการเพิ่มรายชื่อ "${name}" เข้าสู่ระบบคลัง?`,
    EDIT_MOVIE_TITLE: "ยืนยันการแก้ไข",
    ADD_MOVIE_TITLE: "ยืนยันการเพิ่ม",
    EDIT_MOVIE_MSG: (title: string) =>
      `คุณแน่ใจหรือไม่ว่าต้องการบันทึกการแก้ไขของภาพยนตร์เรื่อง "${title}"?`,
    ADD_MOVIE_MSG: (title: string) =>
      `คุณแน่ใจหรือไม่ว่าต้องการเพิ่มภาพยนตร์เรื่อง "${title}" เข้าสู่ระบบพร้อมเผยแพร่?`,
    CANCEL: "ยกเลิก",
    CONFIRM: "ยืนยัน",
  },
  CROP: {
    TITLE: "ตัดแต่งรูปภาพประจำตัว",
    SUBTITLE:
      "ลากเพื่อขยับรูปภาพ และปรับขนาดการซูมเพื่อให้จัดวางใบหน้าลงในวงกลมได้อย่างสวยงาม",
    ZOOM: "ระดับการซูม (Zoom)",
    CANCEL: "ยกเลิก",
    CONFIRM: "เสร็จสิ้น (Crop)",
  },
  COMMON: {
    MOVIES_COUNT: (count: number) => `ภาพยนตร์ (${count})`,
    CONTRIBUTION: (count: number) => `มีส่วนร่วมภาพยนตร์ ${count} เรื่อง`,
  },
  ADMIN: {
    BACK_HOME: "กลับหน้าหลัก",
    DASHBOARD_TITLE: "จัดการภาพยนตร์",
    ADD_MOVIE: "เพิ่มภาพยนตร์ใหม่",
    ADD_CREW: "เพิ่มรายชื่อทีมงาน",
    TOTAL_TITLES: "ภาพยนตร์ทั้งหมด",
    TOTAL_CATEGORIES: "หมวดหมู่ทั้งหมด",
    TOTAL_VIEWS: "ยอดการรับชมรวม",
    TOTAL_CREW: "รายชื่อทีมงานทั้งหมด",
    TAB_MOVIES: (count: number) => `ภาพยนตร์ (${count})`,
    TAB_CREW: (count: number) => `ทีมงาน & นักแสดง (${count})`,
    SEARCH_MOVIE_PLACEHOLDER: "ค้นหาจากชื่อเรื่อง หมวดหมู่ หรือเรื่องย่อ...",
    SEARCH_CREW_PLACEHOLDER: "ค้นหาชื่อทีมงาน / นักแสดง...",
    FILTER_LABEL: "หมวดหมู่:",
    FILTER_ALL: "ทุกหมวดหมู่",
    SORT_LABEL: "เรียงตาม:",
    SORT_ALPHA: "ตามตัวอักษร",
    SORT_YEAR: "ปีที่ฉาย",
    SORT_VIEWS: "ยอดความนิยม",
    NO_MOVIES: "ไม่พบภาพยนตร์ที่ตรงตามตัวกรอง",
    NO_CREW: "ไม่พบรายชื่อทีมงานที่ระบุ",
    TABLE_MOVIE: "ภาพยนตร์",
    TABLE_GENRE: "หมวดหมู่",
    TABLE_RELEASE: "ปีที่ฉาย / เรตติ้ง",
    TABLE_DURATION: "ความยาว",
    TABLE_STATS: "สถิติการเข้าชม",
    TABLE_ACTIONS: "จัดการ",
    TABLE_CREW_NAME: "ชื่อ-นามสกุล",
    TABLE_CREW_STATUS: "สถานะผลงาน",
    TABLE_CREW_DATE: "วันที่บันทึก",
    VIEWS_COUNT: (views: number) => `${views.toLocaleString()} ครั้ง`,
    REVIEWS_COUNT: (reviews: number) => `${reviews} รีวิว`,
    MATCH_RATE: (rate: number) => `${rate}% ตรงกัน`,
  },
  MOVIE_FORM: {
    EDIT_TITLE: "แก้ไขรายละเอียดภาพยนตร์",
    ADD_TITLE: "เพิ่มภาพยนตร์ใหม่",
    SUBTITLE:
      "กรอกข้อมูลภาพยนตร์ให้ถูกต้องและครบถ้วนเพื่อทำการบันทึกเข้าระบบคลังภาพยนตร์",
    TITLE_LABEL: "ชื่อเรื่อง",
    TITLE_PLACEHOLDER: "เช่น Interstellar",
    TITLE_REQUIRED: "กรุณากรอกชื่อเรื่อง",
    CATEGORY_LABEL: "หมวดหมู่",
    CATEGORY_REQUIRED: "กรุณาเลือกหมวดหมู่",
    AGE_LABEL: "เรตอายุที่แนะนำ",
    AGE_REQUIRED: "กรุณาเลือกเรตอายุ",
    YEAR_LABEL: "ปีที่ฉาย",
    YEAR_PLACEHOLDER: "เช่น 2014",
    YEAR_REQUIRED: "กรุณากรอกปีที่ฉาย",
    YEAR_MIN: "ปีที่ฉายต้องไม่เก่ากว่า 1900",
    YEAR_MAX: "ปีที่ฉายต้องไม่เกิน 2100",
    MATCH_LABEL: "ความเหมาะสม (%)",
    MATCH_PLACEHOLDER: "เช่น 98",
    MATCH_REQUIRED: "กรุณากรอกเปอร์เซ็นต์ความเหมาะสม",
    MATCH_MIN: "ขั้นต่ำ 0%",
    MATCH_MAX: "ไม่เกิน 100%",
    DURATION_LABEL: "ความยาวภาพยนตร์ (นาที)",
    DURATION_PLACEHOLDER: "เช่น 120",
    DURATION_REQUIRED: "กรุณากรอกความยาวภาพยนตร์",
    COVER_LABEL: "ภาพปกภาพยนตร์ (Thumbnail)",
    COVER_PLACEHOLDER: "อัปโหลดภาพปกภาพยนตร์...",
    COVER_BROWSE: "เลือกไฟล์",
    COVER_REQUIRED: "กรุณาอัปโหลดภาพปกภาพยนตร์",
    YOUTUBE_LABEL: "ลิงก์ตัวอย่างภาพยนตร์ (YouTube Trailer URL)",
    YOUTUBE_PLACEHOLDER: "https://www.youtube.com/watch?v=...",
    YOUTUBE_REQUIRED: "กรุณากรอกลิงก์ตัวอย่างภาพยนตร์",
    CREW_SECTION_TITLE: "ข้อมูลเบื้องหลัง & ทีมงานผู้สร้าง",
    UNI_LABEL: "สถาบัน / มหาวิทยาลัย",
    UNI_SELECT_PLACEHOLDER: "ไม่ระบุ / เลือกสถาบันการศึกษา...",
    DIRECTOR_LABEL: "ผู้กำกับ (Director)",
    DIRECTOR_PLACEHOLDER: "พิมพ์ชื่อ หรือเลือกผู้กำกับจากคลังรายชื่อ...",
    DIRECTOR_ADD: "เพิ่มรายชื่อผู้กำกับ",
    PRODUCER_LABEL: "ผู้อำนวยการสร้าง (Producer)",
    PRODUCER_PLACEHOLDER: "พิมพ์ชื่อ หรือเลือกผู้อำนวยการสร้าง...",
    PRODUCER_ADD: "เพิ่มรายชื่อผู้อำนวยการสร้าง",
    WRITER_LABEL: "ผู้เขียนบท (Writer)",
    WRITER_PLACEHOLDER: "พิมพ์ชื่อ หรือเลือกผู้เขียนบท...",
    WRITER_ADD: "เพิ่มรายชื่อผู้เขียนบท",
    CAST_LABEL: "นักแสดงนำ (Cast)",
    CAST_PLACEHOLDER: "พิมพ์ชื่อ หรือเลือกนักแสดง...",
    CAST_ADD: "เพิ่มรายชื่อนักแสดง",
    BTS_VIDEO_LABEL: "ลิงก์วิดีโอเบื้องหลัง (YouTube BTS Video)",
    BTS_VIDEO_PLACEHOLDER: "https://www.youtube.com/watch?v=...",
    BTS_VIDEO_ADD: "เพิ่มลิงก์วิดีโอเบื้องหลังอื่น",
    BTS_PHOTO_LABEL: "รูปภาพเบื้องหลัง (BTS Photos)",
    BTS_PHOTO_PLACEHOLDER: "อัปโหลดรูปภาพเบื้องหลัง...",
    BTS_PHOTO_SUBTEXT:
      "สามารถเลือกไฟล์รูปภาพพร้อมกันได้หลายรูปภาพเพื่อสร้างแกลเลอรีเบื้องหลัง",
    BTS_STATUS_SAVED: "บันทึกแล้ว",
    BTS_STATUS_NEW: "รูปใหม่",
    DESC_LABEL: "เรื่องย่อ (Description)",
    DESC_PLACEHOLDER: "กรอกรายละเอียดเรื่องย่อภาพยนตร์เพื่อดึงดูดผู้ชม...",
    DESC_REQUIRED: "กรุณากรอกเรื่องย่อภาพยนตร์",
    CANCEL: "ยกเลิก",
    SAVE: "บันทึกข้อมูลภาพยนตร์",
    ADD: "เพิ่มภาพยนตร์ใหม่",
  },
} as const;
